# Generated by Django 4.2.1 on 2023-06-01 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamodb_adapter", "0002_question_choice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mymodel",
            name="id",
        ),
        migrations.AddField(
            model_name="mymodel",
            name="pub_date",
            field=models.DateTimeField(
                auto_created=True,
                default=django.utils.timezone.now,
                verbose_name="date published",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mymodel",
            name="question_text",
            field=models.CharField(default="sdfgds", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mymodel",
            name="name",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
